deploy:
  tasks:
    - export GIT_REPO=https://github.com/Renice-Owino/Code-With-Kids
    - export TMP_DIR=/tmp/deploy
    - mkdir -p $TMP_DIR
    - git clone $GIT_REPO $TMP_DIR
    - cp -R $TMP_DIR/* .