---
deployment:
  tasks:
    - export DEPLOYPATH="/home/codewith/test.codewithkids.africa"
    # - export GIT_SSH_COMMAND="ssh -i /home/codewith/.ssh/id_rsa"
    # - /bin/bash -c "mkdir -p $DEPLOYPATH"
    # - /bin/bash -c "cd $DEPLOYPATH && git init && git remote add origin git@github.com:Renice-Owino/Code-With-Kids"
    # - /bin/bash -c "cd $DEPLOYPATH && git fetch && git checkout -f level1"
    # - /bin/bash -c "cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader"
    - /bin/cp index.html $DEPLOYPATH
    # https://github.com/Renice-Owino/Code-With-Kids